Spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo_db
    username: postgres
    password: Ken@1224
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
